<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="courseCodeType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2,4}[0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="creditsType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="30"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="courseType">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="professor" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="code" type="courseCodeType" use="required"/>
    <xs:attribute name="credits" type="creditsType" use="required"/>
  </xs:complexType>

  <xs:element name="courses">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="course" type="courseType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
